"""
Stock universe definitions for NSE India.

Start with Nifty 50 — the structure is designed to expand to Nifty 500 easily.
To expand: populate NIFTY500_STOCKS with the same dict format and switch
the UNIVERSE variable in app.py to "NIFTY500".
"""

def _get_custom_stocks_from_db() -> list[dict]:
    """Read universe='CUSTOM' stocks from SQLite. Returns [] if DB unavailable."""
    try:
        from .db import get_connection
        conn = get_connection()
        try:
            cur = conn.cursor()
            cur.execute(
                "SELECT symbol, name, sector FROM stocks WHERE universe = 'CUSTOM' ORDER BY name"
            )
            return [
                {"symbol": r[0], "name": r[1], "sector": r[2] or "Custom"}
                for r in cur.fetchall()
            ]
        finally:
            conn.close()
    except Exception:
        return []

# ─── Nifty 50 ────────────────────────────────────────────────────────────────
# Current constituents as of 2025/2026. Verify against NSE's official list
# at https://www.nseindia.com/products-services/indices-nifty50-index
NIFTY50_STOCKS = [
    {"symbol": "ADANIENT.NS",   "name": "Adani Enterprises",           "sector": "Metals & Mining"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports",                 "sector": "Infrastructure"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals",            "sector": "Healthcare"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints",                "sector": "Consumer Goods"},
    {"symbol": "AXISBANK.NS",   "name": "Axis Bank",                   "sector": "Banking"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto",                  "sector": "Automobile"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv",               "sector": "Financial Services"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance",               "sector": "Financial Services"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel",               "sector": "Telecom"},
    {"symbol": "BPCL.NS",       "name": "BPCL",                        "sector": "Oil & Gas"},
    {"symbol": "BRITANNIA.NS",  "name": "Britannia Industries",        "sector": "FMCG"},
    {"symbol": "CIPLA.NS",      "name": "Cipla",                       "sector": "Pharma"},
    {"symbol": "COALINDIA.NS",  "name": "Coal India",                  "sector": "Metals & Mining"},
    {"symbol": "DIVISLAB.NS",   "name": "Divi's Laboratories",         "sector": "Pharma"},
    {"symbol": "DRREDDY.NS",    "name": "Dr. Reddy's Laboratories",    "sector": "Pharma"},
    {"symbol": "EICHERMOT.NS",  "name": "Eicher Motors",               "sector": "Automobile"},
    {"symbol": "GRASIM.NS",     "name": "Grasim Industries",           "sector": "Cement"},
    {"symbol": "HCLTECH.NS",    "name": "HCL Technologies",            "sector": "IT"},
    {"symbol": "HDFCBANK.NS",   "name": "HDFC Bank",                   "sector": "Banking"},
    {"symbol": "HDFCLIFE.NS",   "name": "HDFC Life Insurance",         "sector": "Insurance"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp",               "sector": "Automobile"},
    {"symbol": "HINDALCO.NS",   "name": "Hindalco Industries",         "sector": "Metals & Mining"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever",          "sector": "FMCG"},
    {"symbol": "ICICIBANK.NS",  "name": "ICICI Bank",                  "sector": "Banking"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank",               "sector": "Banking"},
    {"symbol": "INFY.NS",       "name": "Infosys",                     "sector": "IT"},
    {"symbol": "ITC.NS",        "name": "ITC",                        "sector": "FMCG"},
    {"symbol": "JSWSTEEL.NS",   "name": "JSW Steel",                   "sector": "Metals & Mining"},
    {"symbol": "KOTAKBANK.NS",  "name": "Kotak Mahindra Bank",         "sector": "Banking"},
    {"symbol": "LT.NS",         "name": "Larsen & Toubro",             "sector": "Infrastructure"},
    {"symbol": "M&M.NS",        "name": "Mahindra & Mahindra",         "sector": "Automobile"},
    {"symbol": "MARUTI.NS",     "name": "Maruti Suzuki",               "sector": "Automobile"},
    {"symbol": "NESTLEIND.NS",  "name": "Nestle India",                "sector": "FMCG"},
    {"symbol": "NTPC.NS",       "name": "NTPC",                        "sector": "Power"},
    {"symbol": "ONGC.NS",       "name": "ONGC",                        "sector": "Oil & Gas"},
    {"symbol": "POWERGRID.NS",  "name": "Power Grid Corporation",      "sector": "Power"},
    {"symbol": "RELIANCE.NS",   "name": "Reliance Industries",         "sector": "Oil & Gas"},
    {"symbol": "SBILIFE.NS",    "name": "SBI Life Insurance",          "sector": "Insurance"},
    {"symbol": "SBIN.NS",       "name": "State Bank of India",         "sector": "Banking"},
    {"symbol": "SHRIRAMFIN.NS", "name": "Shriram Finance",             "sector": "Financial Services"},
    {"symbol": "SUNPHARMA.NS",  "name": "Sun Pharmaceutical",          "sector": "Pharma"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products",      "sector": "FMCG"},
    {"symbol": "TMPV.NS",       "name": "Tata Motors PV",              "sector": "Automobile"},
    {"symbol": "TATASTEEL.NS",  "name": "Tata Steel",                  "sector": "Metals & Mining"},
    {"symbol": "TCS.NS",        "name": "Tata Consultancy Services",   "sector": "IT"},
    {"symbol": "TECHM.NS",      "name": "Tech Mahindra",               "sector": "IT"},
    {"symbol": "TITAN.NS",      "name": "Titan Company",               "sector": "Consumer Goods"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement",            "sector": "Cement"},
    {"symbol": "WIPRO.NS",      "name": "Wipro",                       "sector": "IT"},
    {"symbol": "ETERNAL.NS",    "name": "Zomato",                      "sector": "Consumer Tech"},
]

# ─── Nifty 500 placeholder ────────────────────────────────────────────────────
# Populate this list in the same dict format when ready to expand.
# Each entry: {"symbol": "XYZ.NS", "name": "Company Name", "sector": "Sector"}
NIFTY500_STOCKS: list[dict] = [
    {"symbol": "360ONE.NS",     "name": "360 ONE WAM Ltd.",                                     "sector": "Financial Services"},
    {"symbol": "3MINDIA.NS",    "name": "3M India Ltd.",                                        "sector": "Diversified"},
    {"symbol": "AADHARHFC.NS",  "name": "Aadhar Housing Finance Ltd.",                          "sector": "Financial Services"},
    {"symbol": "AARTIIND.NS",   "name": "Aarti Industries Ltd.",                                "sector": "Chemicals"},
    {"symbol": "AAVAS.NS",      "name": "Aavas Financiers Ltd.",                                "sector": "Financial Services"},
    {"symbol": "ABB.NS",        "name": "ABB India Ltd.",                                       "sector": "Capital Goods"},
    {"symbol": "ABBOTINDIA.NS", "name": "Abbott India Ltd.",                                    "sector": "Healthcare"},
    {"symbol": "ABCAPITAL.NS",  "name": "Aditya Birla Capital Ltd.",                            "sector": "Financial Services"},
    {"symbol": "ABDL.NS",       "name": "Allied Blenders and Distillers Ltd.",                  "sector": "FMCG"},
    {"symbol": "ABFRL.NS",      "name": "Aditya Birla Fashion and Retail Ltd.",                 "sector": "Consumer Services"},
    {"symbol": "ABLBL.NS",      "name": "Aditya Birla Lifestyle Brands Ltd.",                   "sector": "Consumer Services"},
    {"symbol": "ABREL.NS",      "name": "Aditya Birla Real Estate Ltd.",                        "sector": "Real Estate"},
    {"symbol": "ABSLAMC.NS",    "name": "Aditya Birla Sun Life AMC Ltd.",                       "sector": "Financial Services"},
    {"symbol": "ACC.NS",        "name": "ACC Ltd.",                                             "sector": "Cement"},
    {"symbol": "ACE.NS",        "name": "Action Construction Equipment Ltd.",                   "sector": "Capital Goods"},
    {"symbol": "ACMESOLAR.NS",  "name": "ACME Solar Holdings Ltd.",                             "sector": "Power"},
    {"symbol": "ACUTAAS.NS",    "name": "Acutaas Chemicals Ltd.",                               "sector": "Healthcare"},
    {"symbol": "ADANIENSOL.NS", "name": "Adani Energy Solutions Ltd.",                          "sector": "Power"},
    {"symbol": "ADANIENT.NS",   "name": "Adani Enterprises Ltd.",                               "sector": "Metals & Mining"},
    {"symbol": "ADANIGREEN.NS", "name": "Adani Green Energy Ltd.",                              "sector": "Power"},
    {"symbol": "ADANIPORTS.NS", "name": "Adani Ports and Special Economic Zone Ltd.",           "sector": "Services"},
    {"symbol": "ADANIPOWER.NS", "name": "Adani Power Ltd.",                                     "sector": "Power"},
    {"symbol": "AEGISLOG.NS",   "name": "Aegis Logistics Ltd.",                                 "sector": "Oil & Gas"},
    {"symbol": "AEGISVOPAK.NS", "name": "Aegis Vopak Terminals Ltd.",                           "sector": "Oil & Gas"},
    {"symbol": "AFCONS.NS",     "name": "Afcons Infrastructure Ltd.",                           "sector": "Infrastructure"},
    {"symbol": "AFFLE.NS",      "name": "Affle 3i Ltd.",                                        "sector": "IT"},
    {"symbol": "AIAENG.NS",     "name": "AIA Engineering Ltd.",                                 "sector": "Capital Goods"},
    {"symbol": "AIIL.NS",       "name": "Authum Investment & Infrastructure Ltd.",              "sector": "Financial Services"},
    {"symbol": "AJANTPHARM.NS", "name": "Ajanta Pharmaceuticals Ltd.",                          "sector": "Healthcare"},
    {"symbol": "ALKEM.NS",      "name": "Alkem Laboratories Ltd.",                              "sector": "Healthcare"},
    {"symbol": "AMBER.NS",      "name": "Amber Enterprises India Ltd.",                         "sector": "Consumer Goods"},
    {"symbol": "AMBUJACEM.NS",  "name": "Ambuja Cements Ltd.",                                  "sector": "Cement"},
    {"symbol": "ANANDRATHI.NS", "name": "Anand Rathi Wealth Ltd.",                              "sector": "Financial Services"},
    {"symbol": "ANANTRAJ.NS",   "name": "Anant Raj Ltd.",                                       "sector": "Real Estate"},
    {"symbol": "ANGELONE.NS",   "name": "Angel One Ltd.",                                       "sector": "Financial Services"},
    {"symbol": "ANTHEM.NS",     "name": "Anthem Biosciences Ltd.",                              "sector": "Healthcare"},
    {"symbol": "ANURAS.NS",     "name": "Anupam Rasayan India Ltd.",                            "sector": "Chemicals"},
    {"symbol": "APARINDS.NS",   "name": "Apar Industries Ltd.",                                 "sector": "Capital Goods"},
    {"symbol": "APLAPOLLO.NS",  "name": "APL Apollo Tubes Ltd.",                                "sector": "Capital Goods"},
    {"symbol": "APOLLOHOSP.NS", "name": "Apollo Hospitals Enterprise Ltd.",                     "sector": "Healthcare"},
    {"symbol": "APOLLOTYRE.NS", "name": "Apollo Tyres Ltd.",                                    "sector": "Automobile"},
    {"symbol": "APTUS.NS",      "name": "Aptus Value Housing Finance India Ltd.",               "sector": "Financial Services"},
    {"symbol": "ARE&M.NS",      "name": "Amara Raja Energy & Mobility Ltd.",                    "sector": "Automobile"},
    {"symbol": "ASAHIINDIA.NS", "name": "Asahi India Glass Ltd.",                               "sector": "Automobile"},
    {"symbol": "ASHOKLEY.NS",   "name": "Ashok Leyland Ltd.",                                   "sector": "Capital Goods"},
    {"symbol": "ASIANPAINT.NS", "name": "Asian Paints Ltd.",                                    "sector": "Consumer Goods"},
    {"symbol": "ASTERDM.NS",    "name": "Aster DM Healthcare Ltd.",                             "sector": "Healthcare"},
    {"symbol": "ASTRAL.NS",     "name": "Astral Ltd.",                                          "sector": "Capital Goods"},
    {"symbol": "ATGL.NS",       "name": "Adani Total Gas Ltd.",                                 "sector": "Oil & Gas"},
    {"symbol": "ATHERENERG.NS", "name": "Ather Energy Ltd.",                                    "sector": "Automobile"},
    {"symbol": "ATUL.NS",       "name": "Atul Ltd.",                                            "sector": "Chemicals"},
    {"symbol": "AUBANK.NS",     "name": "AU Small Finance Bank Ltd.",                           "sector": "Financial Services"},
    {"symbol": "AUROPHARMA.NS", "name": "Aurobindo Pharma Ltd.",                                "sector": "Healthcare"},
    {"symbol": "AWL.NS",        "name": "AWL Agri Business Ltd.",                               "sector": "FMCG"},
    {"symbol": "AXISBANK.NS",   "name": "Axis Bank Ltd.",                                       "sector": "Financial Services"},
    {"symbol": "BAJAJ-AUTO.NS", "name": "Bajaj Auto Ltd.",                                      "sector": "Automobile"},
    {"symbol": "BAJAJFINSV.NS", "name": "Bajaj Finserv Ltd.",                                   "sector": "Financial Services"},
    {"symbol": "BAJAJHFL.NS",   "name": "Bajaj Housing Finance Ltd.",                           "sector": "Financial Services"},
    {"symbol": "BAJAJHLDNG.NS", "name": "Bajaj Holdings & Investment Ltd.",                     "sector": "Financial Services"},
    {"symbol": "BAJFINANCE.NS", "name": "Bajaj Finance Ltd.",                                   "sector": "Financial Services"},
    {"symbol": "BALKRISIND.NS", "name": "Balkrishna Industries Ltd.",                           "sector": "Automobile"},
    {"symbol": "BALRAMCHIN.NS", "name": "Balrampur Chini Mills Ltd.",                           "sector": "FMCG"},
    {"symbol": "BANDHANBNK.NS", "name": "Bandhan Bank Ltd.",                                    "sector": "Financial Services"},
    {"symbol": "BANKBARODA.NS", "name": "Bank of Baroda",                                       "sector": "Financial Services"},
    {"symbol": "BANKINDIA.NS",  "name": "Bank of India",                                        "sector": "Financial Services"},
    {"symbol": "BATAINDIA.NS",  "name": "Bata India Ltd.",                                      "sector": "Consumer Goods"},
    {"symbol": "BAYERCROP.NS",  "name": "Bayer Cropscience Ltd.",                               "sector": "Chemicals"},
    {"symbol": "BBTC.NS",       "name": "Bombay Burmah Trading Corporation Ltd.",               "sector": "FMCG"},
    {"symbol": "BDL.NS",        "name": "Bharat Dynamics Ltd.",                                 "sector": "Capital Goods"},
    {"symbol": "BEL.NS",        "name": "Bharat Electronics Ltd.",                              "sector": "Capital Goods"},
    {"symbol": "BELRISE.NS",    "name": "Belrise Industries Ltd.",                              "sector": "Automobile"},
    {"symbol": "BEML.NS",       "name": "BEML Ltd.",                                            "sector": "Capital Goods"},
    {"symbol": "BERGEPAINT.NS", "name": "Berger Paints India Ltd.",                             "sector": "Consumer Goods"},
    {"symbol": "BHARATFORG.NS", "name": "Bharat Forge Ltd.",                                    "sector": "Automobile"},
    {"symbol": "BHARTIARTL.NS", "name": "Bharti Airtel Ltd.",                                   "sector": "Telecom"},
    {"symbol": "BHARTIHEXA.NS", "name": "Bharti Hexacom Ltd.",                                  "sector": "Telecom"},
    {"symbol": "BHEL.NS",       "name": "Bharat Heavy Electricals Ltd.",                        "sector": "Capital Goods"},
    {"symbol": "BIKAJI.NS",     "name": "Bikaji Foods International Ltd.",                      "sector": "FMCG"},
    {"symbol": "BIOCON.NS",     "name": "Biocon Ltd.",                                          "sector": "Healthcare"},
    {"symbol": "BLS.NS",        "name": "BLS International Services Ltd.",                      "sector": "Consumer Services"},
    {"symbol": "BLUEDART.NS",   "name": "Blue Dart Express Ltd.",                               "sector": "Services"},
    {"symbol": "BLUEJET.NS",    "name": "Blue Jet Healthcare Ltd.",                             "sector": "Healthcare"},
    {"symbol": "BLUESTARCO.NS", "name": "Blue Star Ltd.",                                       "sector": "Consumer Goods"},
    {"symbol": "BOSCHLTD.NS",   "name": "Bosch Ltd.",                                           "sector": "Automobile"},
    {"symbol": "BPCL.NS",       "name": "Bharat Petroleum Corporation Ltd.",                    "sector": "Oil & Gas"},
    {"symbol": "BRIGADE.NS",    "name": "Brigade Enterprises Ltd.",                             "sector": "Real Estate"},
    {"symbol": "BRITANNIA.NS",  "name": "Britannia Industries Ltd.",                            "sector": "FMCG"},
    {"symbol": "BSE.NS",        "name": "BSE Ltd.",                                             "sector": "Financial Services"},
    {"symbol": "BSOFT.NS",      "name": "Birlasoft Ltd.",                                       "sector": "IT"},
    {"symbol": "CAMS.NS",       "name": "Computer Age Management Services Ltd.",                "sector": "Financial Services"},
    {"symbol": "CANBK.NS",      "name": "Canara Bank",                                          "sector": "Financial Services"},
    {"symbol": "CANFINHOME.NS", "name": "Can Fin Homes Ltd.",                                   "sector": "Financial Services"},
    {"symbol": "CANHLIFE.NS",   "name": "Canara HSBC Life Insurance Company Ltd.",              "sector": "Financial Services"},
    {"symbol": "CAPLIPOINT.NS", "name": "Caplin Point Laboratories Ltd.",                       "sector": "Healthcare"},
    {"symbol": "CARBORUNIV.NS", "name": "Carborundum Universal Ltd.",                           "sector": "Capital Goods"},
    {"symbol": "CARTRADE.NS",   "name": "Cartrade Tech Ltd.",                                   "sector": "Consumer Services"},
    {"symbol": "CASTROLIND.NS", "name": "Castrol India Ltd.",                                   "sector": "Oil & Gas"},
    {"symbol": "CCL.NS",        "name": "CCL Products (I) Ltd.",                                "sector": "FMCG"},
    {"symbol": "CDSL.NS",       "name": "Central Depository Services (India) Ltd.",             "sector": "Financial Services"},
    {"symbol": "CEATLTD.NS",    "name": "Ceat Ltd.",                                            "sector": "Automobile"},
    {"symbol": "CEMPRO.NS",     "name": "Cemindia Projects Ltd.",                               "sector": "Infrastructure"},
    {"symbol": "CENTRALBK.NS",  "name": "Central Bank of India",                                "sector": "Financial Services"},
    {"symbol": "CESC.NS",       "name": "CESC Ltd.",                                            "sector": "Power"},
    {"symbol": "CGCL.NS",       "name": "Capri Global Capital Ltd.",                            "sector": "Financial Services"},
    {"symbol": "CGPOWER.NS",    "name": "CG Power and Industrial Solutions Ltd.",               "sector": "Capital Goods"},
    {"symbol": "CHALET.NS",     "name": "Chalet Hotels Ltd.",                                   "sector": "Consumer Services"},
    {"symbol": "CHAMBLFERT.NS", "name": "Chambal Fertilizers & Chemicals Ltd.",                 "sector": "Chemicals"},
    {"symbol": "CHENNPETRO.NS", "name": "Chennai Petroleum Corporation Ltd.",                   "sector": "Oil & Gas"},
    {"symbol": "CHOICEIN.NS",   "name": "Choice International Ltd.",                            "sector": "Financial Services"},
    {"symbol": "CHOLAFIN.NS",   "name": "Cholamandalam Investment and Finance Company Ltd.",    "sector": "Financial Services"},
    {"symbol": "CHOLAHLDNG.NS", "name": "Cholamandalam Financial Holdings Ltd.",                "sector": "Financial Services"},
    {"symbol": "CIPLA.NS",      "name": "Cipla Ltd.",                                           "sector": "Healthcare"},
    {"symbol": "CLEAN.NS",      "name": "Clean Science and Technology Ltd.",                    "sector": "Chemicals"},
    {"symbol": "COALINDIA.NS",  "name": "Coal India Ltd.",                                      "sector": "Oil & Gas"},
    {"symbol": "COCHINSHIP.NS", "name": "Cochin Shipyard Ltd.",                                 "sector": "Capital Goods"},
    {"symbol": "COFORGE.NS",    "name": "Coforge Ltd.",                                         "sector": "IT"},
    {"symbol": "COHANCE.NS",    "name": "Cohance Lifesciences Ltd.",                            "sector": "Healthcare"},
    {"symbol": "COLPAL.NS",     "name": "Colgate Palmolive (India) Ltd.",                       "sector": "FMCG"},
    {"symbol": "CONCOR.NS",     "name": "Container Corporation of India Ltd.",                  "sector": "Services"},
    {"symbol": "CONCORDBIO.NS", "name": "Concord Biotech Ltd.",                                 "sector": "Healthcare"},
    {"symbol": "COROMANDEL.NS", "name": "Coromandel International Ltd.",                        "sector": "Chemicals"},
    {"symbol": "CPPLUS.NS",     "name": "Aditya Infotech Ltd.",                                 "sector": "Capital Goods"},
    {"symbol": "CRAFTSMAN.NS",  "name": "Craftsman Automation Ltd.",                            "sector": "Automobile"},
    {"symbol": "CREDITACC.NS",  "name": "CreditAccess Grameen Ltd.",                            "sector": "Financial Services"},
    {"symbol": "CRISIL.NS",     "name": "CRISIL Ltd.",                                          "sector": "Financial Services"},
    {"symbol": "CROMPTON.NS",   "name": "Crompton Greaves Consumer Electricals Ltd.",           "sector": "Consumer Goods"},
    {"symbol": "CUB.NS",        "name": "City Union Bank Ltd.",                                 "sector": "Financial Services"},
    {"symbol": "CUMMINSIND.NS", "name": "Cummins India Ltd.",                                   "sector": "Capital Goods"},
    {"symbol": "CYIENT.NS",     "name": "Cyient Ltd.",                                          "sector": "IT"},
    {"symbol": "DABUR.NS",      "name": "Dabur India Ltd.",                                     "sector": "FMCG"},
    {"symbol": "DALBHARAT.NS",  "name": "Dalmia Bharat Ltd.",                                   "sector": "Cement"},
    {"symbol": "DATAPATTNS.NS", "name": "Data Patterns (India) Ltd.",                           "sector": "Capital Goods"},
    {"symbol": "DCMSHRIRAM.NS", "name": "DCM Shriram Ltd.",                                     "sector": "Diversified"},
    {"symbol": "DEEPAKFERT.NS", "name": "Deepak Fertilisers & Petrochemicals Corp. Ltd.",       "sector": "Chemicals"},
    {"symbol": "DEEPAKNTR.NS",  "name": "Deepak Nitrite Ltd.",                                  "sector": "Chemicals"},
    {"symbol": "DELHIVERY.NS",  "name": "Delhivery Ltd.",                                       "sector": "Services"},
    {"symbol": "DEVYANI.NS",    "name": "Devyani International Ltd.",                           "sector": "Consumer Services"},
    {"symbol": "DIVISLAB.NS",   "name": "Divi's Laboratories Ltd.",                             "sector": "Healthcare"},
    {"symbol": "DIXON.NS",      "name": "Dixon Technologies (India) Ltd.",                      "sector": "Consumer Goods"},
    {"symbol": "DLF.NS",        "name": "DLF Ltd.",                                             "sector": "Real Estate"},
    {"symbol": "DMART.NS",      "name": "Avenue Supermarts Ltd.",                               "sector": "Consumer Services"},
    {"symbol": "DOMS.NS",       "name": "DOMS Industries Ltd.",                                 "sector": "FMCG"},
    {"symbol": "DRREDDY.NS",    "name": "Dr. Reddy's Laboratories Ltd.",                        "sector": "Healthcare"},
    {"symbol": "DUMMYVEDL1.NS", "name": "Dummy Vedanta Ltd. 1",                                 "sector": "Metals & Mining"},
    {"symbol": "DUMMYVEDL2.NS", "name": "Dummy Vedanta Ltd. 2",                                 "sector": "Power"},
    {"symbol": "DUMMYVEDL3.NS", "name": "Dummy Vedanta Ltd. 3",                                 "sector": "Oil & Gas"},
    {"symbol": "DUMMYVEDL4.NS", "name": "Dummy Vedanta Ltd. 4",                                 "sector": "Metals & Mining"},
    {"symbol": "ECLERX.NS",     "name": "eClerx Services Ltd.",                                 "sector": "Services"},
    {"symbol": "EICHERMOT.NS",  "name": "Eicher Motors Ltd.",                                   "sector": "Automobile"},
    {"symbol": "EIDPARRY.NS",   "name": "E.I.D. Parry (India) Ltd.",                            "sector": "FMCG"},
    {"symbol": "EIHOTEL.NS",    "name": "EIH Ltd.",                                             "sector": "Consumer Services"},
    {"symbol": "ELECON.NS",     "name": "Elecon Engineering Co. Ltd.",                          "sector": "Capital Goods"},
    {"symbol": "ELGIEQUIP.NS",  "name": "Elgi Equipments Ltd.",                                 "sector": "Capital Goods"},
    {"symbol": "EMAMILTD.NS",   "name": "Emami Ltd.",                                           "sector": "FMCG"},
    {"symbol": "EMCURE.NS",     "name": "Emcure Pharmaceuticals Ltd.",                          "sector": "Healthcare"},
    {"symbol": "EMMVEE.NS",     "name": "Emmvee Photovoltaic Power Ltd.",                       "sector": "Capital Goods"},
    {"symbol": "ENDURANCE.NS",  "name": "Endurance Technologies Ltd.",                          "sector": "Automobile"},
    {"symbol": "ENGINERSIN.NS", "name": "Engineers India Ltd.",                                 "sector": "Infrastructure"},
    {"symbol": "ENRIN.NS",      "name": "Siemens Energy India Ltd.",                            "sector": "Capital Goods"},
    {"symbol": "ERIS.NS",       "name": "Eris Lifesciences Ltd.",                               "sector": "Healthcare"},
    {"symbol": "ESCORTS.NS",    "name": "Escorts Kubota Ltd.",                                  "sector": "Capital Goods"},
    {"symbol": "ETERNAL.NS",    "name": "Eternal Ltd.",                                         "sector": "Consumer Services"},
    {"symbol": "EXIDEIND.NS",   "name": "Exide Industries Ltd.",                                "sector": "Automobile"},
    {"symbol": "FACT.NS",       "name": "Fertilisers and Chemicals Travancore Ltd.",            "sector": "Chemicals"},
    {"symbol": "FEDERALBNK.NS", "name": "Federal Bank Ltd.",                                    "sector": "Financial Services"},
    {"symbol": "FINCABLES.NS",  "name": "Finolex Cables Ltd.",                                  "sector": "Capital Goods"},
    {"symbol": "FIRSTCRY.NS",   "name": "Brainbees Solutions Ltd.",                             "sector": "Consumer Services"},
    {"symbol": "FIVESTAR.NS",   "name": "Five-Star Business Finance Ltd.",                      "sector": "Financial Services"},
    {"symbol": "FLUOROCHEM.NS", "name": "Gujarat Fluorochemicals Ltd.",                         "sector": "Chemicals"},
    {"symbol": "FORCEMOT.NS",   "name": "Force Motors Ltd.",                                    "sector": "Automobile"},
    {"symbol": "FORTIS.NS",     "name": "Fortis Healthcare Ltd.",                               "sector": "Healthcare"},
    {"symbol": "FSL.NS",        "name": "Firstsource Solutions Ltd.",                           "sector": "Services"},
    {"symbol": "GABRIEL.NS",    "name": "Gabriel India Ltd.",                                   "sector": "Automobile"},
    {"symbol": "GAIL.NS",       "name": "GAIL (India) Ltd.",                                    "sector": "Oil & Gas"},
    {"symbol": "GALLANTT.NS",   "name": "Gallantt Ispat Ltd.",                                  "sector": "Capital Goods"},
    {"symbol": "GESHIP.NS",     "name": "Great Eastern Shipping Co. Ltd.",                      "sector": "Services"},
    {"symbol": "GICRE.NS",      "name": "General Insurance Corporation of India",               "sector": "Financial Services"},
    {"symbol": "GILLETTE.NS",   "name": "Gillette India Ltd.",                                  "sector": "FMCG"},
    {"symbol": "GLAND.NS",      "name": "Gland Pharma Ltd.",                                    "sector": "Healthcare"},
    {"symbol": "GLAXO.NS",      "name": "Glaxosmithkline Pharmaceuticals Ltd.",                 "sector": "Healthcare"},
    {"symbol": "GLENMARK.NS",   "name": "Glenmark Pharmaceuticals Ltd.",                        "sector": "Healthcare"},
    {"symbol": "GMDCLTD.NS",    "name": "Gujarat Mineral Development Corporation Ltd.",         "sector": "Metals & Mining"},
    {"symbol": "GMRAIRPORT.NS", "name": "GMR Airports Ltd.",                                    "sector": "Services"},
    {"symbol": "GODFRYPHLP.NS", "name": "Godfrey Phillips India Ltd.",                          "sector": "FMCG"},
    {"symbol": "GODIGIT.NS",    "name": "Go Digit General Insurance Ltd.",                      "sector": "Financial Services"},
    {"symbol": "GODREJCP.NS",   "name": "Godrej Consumer Products Ltd.",                        "sector": "FMCG"},
    {"symbol": "GODREJIND.NS",  "name": "Godrej Industries Ltd.",                               "sector": "Diversified"},
    {"symbol": "GODREJPROP.NS", "name": "Godrej Properties Ltd.",                               "sector": "Real Estate"},
    {"symbol": "GPIL.NS",       "name": "Godawari Power & Ispat Ltd.",                          "sector": "Capital Goods"},
    {"symbol": "GRANULES.NS",   "name": "Granules India Ltd.",                                  "sector": "Healthcare"},
    {"symbol": "GRAPHITE.NS",   "name": "Graphite India Ltd.",                                  "sector": "Capital Goods"},
    {"symbol": "GRASIM.NS",     "name": "Grasim Industries Ltd.",                               "sector": "Cement"},
    {"symbol": "GRAVITA.NS",    "name": "Gravita India Ltd.",                                   "sector": "Metals & Mining"},
    {"symbol": "GROWW.NS",      "name": "Billionbrains Garage Ventures Ltd.",                   "sector": "Financial Services"},
    {"symbol": "GRSE.NS",       "name": "Garden Reach Shipbuilders & Engineers Ltd.",           "sector": "Capital Goods"},
    {"symbol": "GSPL.NS",       "name": "Gujarat State Petronet Ltd.",                          "sector": "Oil & Gas"},
    {"symbol": "GVT&D.NS",      "name": "GE Vernova T&D India Ltd.",                            "sector": "Capital Goods"},
    {"symbol": "HAL.NS",        "name": "Hindustan Aeronautics Ltd.",                           "sector": "Capital Goods"},
    {"symbol": "HAVELLS.NS",    "name": "Havells India Ltd.",                                   "sector": "Consumer Goods"},
    {"symbol": "HBLENGINE.NS",  "name": "HBL Engineering Ltd.",                                 "sector": "Capital Goods"},
    {"symbol": "HCLTECH.NS",    "name": "HCL Technologies Ltd.",                                "sector": "IT"},
    {"symbol": "HDBFS.NS",      "name": "HDB Financial Services Ltd.",                          "sector": "Financial Services"},
    {"symbol": "HDFCAMC.NS",    "name": "HDFC Asset Management Company Ltd.",                   "sector": "Financial Services"},
    {"symbol": "HDFCBANK.NS",   "name": "HDFC Bank Ltd.",                                       "sector": "Financial Services"},
    {"symbol": "HDFCLIFE.NS",   "name": "HDFC Life Insurance Company Ltd.",                     "sector": "Financial Services"},
    {"symbol": "HEG.NS",        "name": "H.E.G. Ltd.",                                          "sector": "Capital Goods"},
    {"symbol": "HEROMOTOCO.NS", "name": "Hero MotoCorp Ltd.",                                   "sector": "Automobile"},
    {"symbol": "HEXT.NS",       "name": "Hexaware Technologies Ltd.",                           "sector": "IT"},
    {"symbol": "HFCL.NS",       "name": "HFCL Ltd.",                                            "sector": "Telecom"},
    {"symbol": "HINDALCO.NS",   "name": "Hindalco Industries Ltd.",                             "sector": "Metals & Mining"},
    {"symbol": "HINDCOPPER.NS", "name": "Hindustan Copper Ltd.",                                "sector": "Metals & Mining"},
    {"symbol": "HINDPETRO.NS",  "name": "Hindustan Petroleum Corporation Ltd.",                 "sector": "Oil & Gas"},
    {"symbol": "HINDUNILVR.NS", "name": "Hindustan Unilever Ltd.",                              "sector": "FMCG"},
    {"symbol": "HINDZINC.NS",   "name": "Hindustan Zinc Ltd.",                                  "sector": "Metals & Mining"},
    {"symbol": "HOMEFIRST.NS",  "name": "Home First Finance Company India Ltd.",                "sector": "Financial Services"},
    {"symbol": "HONASA.NS",     "name": "Honasa Consumer Ltd.",                                 "sector": "FMCG"},
    {"symbol": "HONAUT.NS",     "name": "Honeywell Automation India Ltd.",                      "sector": "Capital Goods"},
    {"symbol": "HSCL.NS",       "name": "Himadri Speciality Chemical Ltd.",                     "sector": "Chemicals"},
    {"symbol": "HUDCO.NS",      "name": "Housing & Urban Development Corporation Ltd.",         "sector": "Financial Services"},
    {"symbol": "HYUNDAI.NS",    "name": "Hyundai Motor India Ltd.",                             "sector": "Automobile"},
    {"symbol": "ICICIAMC.NS",   "name": "ICICI Prudential Asset Management Company Ltd.",       "sector": "Financial Services"},
    {"symbol": "ICICIBANK.NS",  "name": "ICICI Bank Ltd.",                                      "sector": "Financial Services"},
    {"symbol": "ICICIGI.NS",    "name": "ICICI Lombard General Insurance Company Ltd.",         "sector": "Financial Services"},
    {"symbol": "ICICIPRULI.NS", "name": "ICICI Prudential Life Insurance Company Ltd.",         "sector": "Financial Services"},
    {"symbol": "IDBI.NS",       "name": "IDBI Bank Ltd.",                                       "sector": "Financial Services"},
    {"symbol": "IDEA.NS",       "name": "Vodafone Idea Ltd.",                                   "sector": "Telecom"},
    {"symbol": "IDFCFIRSTB.NS", "name": "IDFC First Bank Ltd.",                                 "sector": "Financial Services"},
    {"symbol": "IEX.NS",        "name": "Indian Energy Exchange Ltd.",                          "sector": "Financial Services"},
    {"symbol": "IFCI.NS",       "name": "IFCI Ltd.",                                            "sector": "Financial Services"},
    {"symbol": "IGIL.NS",       "name": "International Gemmological Institute (India) Ltd.",    "sector": "Services"},
    {"symbol": "IGL.NS",        "name": "Indraprastha Gas Ltd.",                                "sector": "Oil & Gas"},
    {"symbol": "IIFL.NS",       "name": "IIFL Finance Ltd.",                                    "sector": "Financial Services"},
    {"symbol": "IKS.NS",        "name": "Inventurus Knowledge Solutions Ltd.",                  "sector": "IT"},
    {"symbol": "INDGN.NS",      "name": "Indegene Ltd.",                                        "sector": "Healthcare"},
    {"symbol": "INDHOTEL.NS",   "name": "Indian Hotels Co. Ltd.",                               "sector": "Consumer Services"},
    {"symbol": "INDIACEM.NS",   "name": "India Cements Ltd.",                                   "sector": "Cement"},
    {"symbol": "INDIAMART.NS",  "name": "Indiamart Intermesh Ltd.",                             "sector": "Consumer Services"},
    {"symbol": "INDIANB.NS",    "name": "Indian Bank",                                          "sector": "Financial Services"},
    {"symbol": "INDIGO.NS",     "name": "InterGlobe Aviation Ltd.",                             "sector": "Services"},
    {"symbol": "INDUSINDBK.NS", "name": "IndusInd Bank Ltd.",                                   "sector": "Financial Services"},
    {"symbol": "INDUSTOWER.NS", "name": "Indus Towers Ltd.",                                    "sector": "Telecom"},
    {"symbol": "INFY.NS",       "name": "Infosys Ltd.",                                         "sector": "IT"},
    {"symbol": "INOXWIND.NS",   "name": "Inox Wind Ltd.",                                       "sector": "Capital Goods"},
    {"symbol": "INTELLECT.NS",  "name": "Intellect Design Arena Ltd.",                          "sector": "IT"},
    {"symbol": "IOB.NS",        "name": "Indian Overseas Bank",                                 "sector": "Financial Services"},
    {"symbol": "IOC.NS",        "name": "Indian Oil Corporation Ltd.",                          "sector": "Oil & Gas"},
    {"symbol": "IPCALAB.NS",    "name": "Ipca Laboratories Ltd.",                               "sector": "Healthcare"},
    {"symbol": "IRB.NS",        "name": "IRB Infrastructure Developers Ltd.",                   "sector": "Infrastructure"},
    {"symbol": "IRCON.NS",      "name": "IRCON International Ltd.",                             "sector": "Infrastructure"},
    {"symbol": "IRCTC.NS",      "name": "Indian Railway Catering And Tourism Corporation Ltd.", "sector": "Consumer Services"},
    {"symbol": "IREDA.NS",      "name": "Indian Renewable Energy Development Agency Ltd.",      "sector": "Financial Services"},
    {"symbol": "IRFC.NS",       "name": "Indian Railway Finance Corporation Ltd.",              "sector": "Financial Services"},
    {"symbol": "ITC.NS",        "name": "ITC Ltd.",                                             "sector": "FMCG"},
    {"symbol": "ITCHOTELS.NS",  "name": "ITC Hotels Ltd.",                                      "sector": "Consumer Services"},
    {"symbol": "ITI.NS",        "name": "ITI Ltd.",                                             "sector": "Telecom"},
    {"symbol": "J&KBANK.NS",    "name": "Jammu & Kashmir Bank Ltd.",                            "sector": "Financial Services"},
    {"symbol": "JAINREC.NS",    "name": "Jain Resource Recycling Ltd.",                         "sector": "Metals & Mining"},
    {"symbol": "JBCHEPHARM.NS", "name": "J.B. Chemicals & Pharmaceuticals Ltd.",                "sector": "Healthcare"},
    {"symbol": "JBMA.NS",       "name": "JBM Auto Ltd.",                                        "sector": "Automobile"},
    {"symbol": "JINDALSAW.NS",  "name": "Jindal Saw Ltd.",                                      "sector": "Capital Goods"},
    {"symbol": "JINDALSTEL.NS", "name": "Jindal Steel Ltd.",                                    "sector": "Metals & Mining"},
    {"symbol": "JIOFIN.NS",     "name": "Jio Financial Services Ltd.",                          "sector": "Financial Services"},
    {"symbol": "JKCEMENT.NS",   "name": "J.K. Cement Ltd.",                                     "sector": "Cement"},
    {"symbol": "JKTYRE.NS",     "name": "JK Tyre & Industries Ltd.",                            "sector": "Automobile"},
    {"symbol": "JMFINANCIL.NS", "name": "JM Financial Ltd.",                                    "sector": "Financial Services"},
    {"symbol": "JPPOWER.NS",    "name": "Jaiprakash Power Ventures Ltd.",                       "sector": "Power"},
    {"symbol": "JSL.NS",        "name": "Jindal Stainless Ltd.",                                "sector": "Metals & Mining"},
    {"symbol": "JSWCEMENT.NS",  "name": "JSW Cement Ltd.",                                      "sector": "Cement"},
    {"symbol": "JSWDULUX.NS",   "name": "JSW Dulux Ltd.",                                       "sector": "Consumer Goods"},
    {"symbol": "JSWENERGY.NS",  "name": "JSW Energy Ltd.",                                      "sector": "Power"},
    {"symbol": "JSWINFRA.NS",   "name": "JSW Infrastructure Ltd.",                              "sector": "Services"},
    {"symbol": "JSWSTEEL.NS",   "name": "JSW Steel Ltd.",                                       "sector": "Metals & Mining"},
    {"symbol": "JUBLFOOD.NS",   "name": "Jubilant Foodworks Ltd.",                              "sector": "Consumer Services"},
    {"symbol": "JUBLINGREA.NS", "name": "Jubilant Ingrevia Ltd.",                               "sector": "Chemicals"},
    {"symbol": "JUBLPHARMA.NS", "name": "Jubilant Pharmova Ltd.",                               "sector": "Healthcare"},
    {"symbol": "JWL.NS",        "name": "Jupiter Wagons Ltd.",                                  "sector": "Capital Goods"},
    {"symbol": "JYOTICNC.NS",   "name": "Jyoti CNC Automation Ltd.",                            "sector": "Capital Goods"},
    {"symbol": "KAJARIACER.NS", "name": "Kajaria Ceramics Ltd.",                                "sector": "Consumer Goods"},
    {"symbol": "KALYANKJIL.NS", "name": "Kalyan Jewellers India Ltd.",                          "sector": "Consumer Goods"},
    {"symbol": "KARURVYSYA.NS", "name": "Karur Vysya Bank Ltd.",                                "sector": "Financial Services"},
    {"symbol": "KAYNES.NS",     "name": "Kaynes Technology India Ltd.",                         "sector": "Capital Goods"},
    {"symbol": "KEC.NS",        "name": "Kec International Ltd.",                               "sector": "Infrastructure"},
    {"symbol": "KEI.NS",        "name": "KEI Industries Ltd.",                                  "sector": "Capital Goods"},
    {"symbol": "KFINTECH.NS",   "name": "Kfin Technologies Ltd.",                               "sector": "Financial Services"},
    {"symbol": "KIMS.NS",       "name": "Krishna Institute of Medical Sciences Ltd.",           "sector": "Healthcare"},
    {"symbol": "KIRLOSENG.NS",  "name": "Kirloskar Oil Eng Ltd.",                               "sector": "Capital Goods"},
    {"symbol": "KOTAKBANK.NS",  "name": "Kotak Mahindra Bank Ltd.",                             "sector": "Financial Services"},
    {"symbol": "KPIL.NS",       "name": "Kalpataru Projects International Ltd.",                "sector": "Infrastructure"},
    {"symbol": "KPITTECH.NS",   "name": "KPIT Technologies Ltd.",                               "sector": "IT"},
    {"symbol": "KPRMILL.NS",    "name": "K.P.R. Mill Ltd.",                                     "sector": "Textiles"},
    {"symbol": "LALPATHLAB.NS", "name": "Dr. Lal Path Labs Ltd.",                               "sector": "Healthcare"},
    {"symbol": "LATENTVIEW.NS", "name": "Latent View Analytics Ltd.",                           "sector": "IT"},
    {"symbol": "LAURUSLABS.NS", "name": "Laurus Labs Ltd.",                                     "sector": "Healthcare"},
    {"symbol": "LEMONTREE.NS",  "name": "Lemon Tree Hotels Ltd.",                               "sector": "Consumer Services"},
    {"symbol": "LENSKART.NS",   "name": "Lenskart Solutions Ltd.",                              "sector": "Consumer Services"},
    {"symbol": "LGEINDIA.NS",   "name": "LG Electronics India Ltd.",                            "sector": "Consumer Goods"},
    {"symbol": "LICHSGFIN.NS",  "name": "LIC Housing Finance Ltd.",                             "sector": "Financial Services"},
    {"symbol": "LICI.NS",       "name": "Life Insurance Corporation of India",                  "sector": "Financial Services"},
    {"symbol": "LINDEINDIA.NS", "name": "Linde India Ltd.",                                     "sector": "Chemicals"},
    {"symbol": "LLOYDSME.NS",   "name": "Lloyds Metals And Energy Ltd.",                        "sector": "Metals & Mining"},
    {"symbol": "LODHA.NS",      "name": "Lodha Developers Ltd.",                                "sector": "Real Estate"},
    {"symbol": "LT.NS",         "name": "Larsen & Toubro Ltd.",                                 "sector": "Infrastructure"},
    {"symbol": "LTF.NS",        "name": "L&T Finance Ltd.",                                     "sector": "Financial Services"},
    {"symbol": "LTFOODS.NS",    "name": "LT Foods Ltd.",                                        "sector": "FMCG"},
    {"symbol": "LTM.NS",        "name": "LTM Ltd.",                                             "sector": "IT"},
    {"symbol": "LTTS.NS",       "name": "L&T Technology Services Ltd.",                         "sector": "IT"},
    {"symbol": "LUPIN.NS",      "name": "Lupin Ltd.",                                           "sector": "Healthcare"},
    {"symbol": "M&M.NS",        "name": "Mahindra & Mahindra Ltd.",                             "sector": "Automobile"},
    {"symbol": "M&MFIN.NS",     "name": "Mahindra & Mahindra Financial Services Ltd.",          "sector": "Financial Services"},
    {"symbol": "MAHABANK.NS",   "name": "Bank of Maharashtra",                                  "sector": "Financial Services"},
    {"symbol": "MANAPPURAM.NS", "name": "Manappuram Finance Ltd.",                              "sector": "Financial Services"},
    {"symbol": "MANKIND.NS",    "name": "Mankind Pharma Ltd.",                                  "sector": "Healthcare"},
    {"symbol": "MAPMYINDIA.NS", "name": "C.E. Info Systems Ltd.",                               "sector": "IT"},
    {"symbol": "MARICO.NS",     "name": "Marico Ltd.",                                          "sector": "FMCG"},
    {"symbol": "MARUTI.NS",     "name": "Maruti Suzuki India Ltd.",                             "sector": "Automobile"},
    {"symbol": "MAXHEALTH.NS",  "name": "Max Healthcare Institute Ltd.",                        "sector": "Healthcare"},
    {"symbol": "MAZDOCK.NS",    "name": "Mazagoan Dock Shipbuilders Ltd.",                      "sector": "Capital Goods"},
    {"symbol": "MCX.NS",        "name": "Multi Commodity Exchange of India Ltd.",               "sector": "Financial Services"},
    {"symbol": "MEDANTA.NS",    "name": "Global Health Ltd.",                                   "sector": "Healthcare"},
    {"symbol": "MEESHO.NS",     "name": "Meesho Ltd.",                                          "sector": "Consumer Services"},
    {"symbol": "MFSL.NS",       "name": "Max Financial Services Ltd.",                          "sector": "Financial Services"},
    {"symbol": "MGL.NS",        "name": "Mahanagar Gas Ltd.",                                   "sector": "Oil & Gas"},
    {"symbol": "MINDACORP.NS",  "name": "Minda Corporation Ltd.",                               "sector": "Automobile"},
    {"symbol": "MMTC.NS",       "name": "MMTC Ltd.",                                            "sector": "Services"},
    {"symbol": "MOTHERSON.NS",  "name": "Samvardhana Motherson International Ltd.",             "sector": "Automobile"},
    {"symbol": "MOTILALOFS.NS", "name": "Motilal Oswal Financial Services Ltd.",                "sector": "Financial Services"},
    {"symbol": "MPHASIS.NS",    "name": "MphasiS Ltd.",                                         "sector": "IT"},
    {"symbol": "MRF.NS",        "name": "MRF Ltd.",                                             "sector": "Automobile"},
    {"symbol": "MRPL.NS",       "name": "Mangalore Refinery & Petrochemicals Ltd.",             "sector": "Oil & Gas"},
    {"symbol": "MSUMI.NS",      "name": "Motherson Sumi Wiring India Ltd.",                     "sector": "Automobile"},
    {"symbol": "MUTHOOTFIN.NS", "name": "Muthoot Finance Ltd.",                                 "sector": "Financial Services"},
    {"symbol": "NAM-INDIA.NS",  "name": "Nippon Life India Asset Management Ltd.",              "sector": "Financial Services"},
    {"symbol": "NATCOPHARM.NS", "name": "NATCO Pharma Ltd.",                                    "sector": "Healthcare"},
    {"symbol": "NATIONALUM.NS", "name": "National Aluminium Co. Ltd.",                          "sector": "Metals & Mining"},
    {"symbol": "NAUKRI.NS",     "name": "Info Edge (India) Ltd.",                               "sector": "Consumer Services"},
    {"symbol": "NAVA.NS",       "name": "Nava Ltd.",                                            "sector": "Power"},
    {"symbol": "NAVINFLUOR.NS", "name": "Navin Fluorine International Ltd.",                    "sector": "Chemicals"},
    {"symbol": "NBCC.NS",       "name": "NBCC (India) Ltd.",                                    "sector": "Infrastructure"},
    {"symbol": "NCC.NS",        "name": "NCC Ltd.",                                             "sector": "Infrastructure"},
    {"symbol": "NESTLEIND.NS",  "name": "Nestle India Ltd.",                                    "sector": "FMCG"},
    {"symbol": "NETWEB.NS",     "name": "Netweb Technologies India Ltd.",                       "sector": "IT"},
    {"symbol": "NEULANDLAB.NS", "name": "Neuland Laboratories Ltd.",                            "sector": "Healthcare"},
    {"symbol": "NEWGEN.NS",     "name": "Newgen Software Technologies Ltd.",                    "sector": "IT"},
    {"symbol": "NH.NS",         "name": "Narayana Hrudayalaya Ltd.",                            "sector": "Healthcare"},
    {"symbol": "NHPC.NS",       "name": "NHPC Ltd.",                                            "sector": "Power"},
    {"symbol": "NIACL.NS",      "name": "The New India Assurance Company Ltd.",                 "sector": "Financial Services"},
    {"symbol": "NIVABUPA.NS",   "name": "Niva Bupa Health Insurance Company Ltd.",              "sector": "Financial Services"},
    {"symbol": "NLCINDIA.NS",   "name": "NLC India Ltd.",                                       "sector": "Power"},
    {"symbol": "NMDC.NS",       "name": "NMDC Ltd.",                                            "sector": "Metals & Mining"},
    {"symbol": "NSLNISP.NS",    "name": "NMDC Steel Ltd.",                                      "sector": "Metals & Mining"},
    {"symbol": "NTPC.NS",       "name": "NTPC Ltd.",                                            "sector": "Power"},
    {"symbol": "NTPCGREEN.NS",  "name": "NTPC Green Energy Ltd.",                               "sector": "Power"},
    {"symbol": "NUVAMA.NS",     "name": "Nuvama Wealth Management Ltd.",                        "sector": "Financial Services"},
    {"symbol": "NUVOCO.NS",     "name": "Nuvoco Vistas Corporation Ltd.",                       "sector": "Cement"},
    {"symbol": "NYKAA.NS",      "name": "FSN E-Commerce Ventures Ltd.",                         "sector": "Consumer Services"},
    {"symbol": "OBEROIRLTY.NS", "name": "Oberoi Realty Ltd.",                                   "sector": "Real Estate"},
    {"symbol": "OFSS.NS",       "name": "Oracle Financial Services Software Ltd.",              "sector": "IT"},
    {"symbol": "OIL.NS",        "name": "Oil India Ltd.",                                       "sector": "Oil & Gas"},
    {"symbol": "OLAELEC.NS",    "name": "Ola Electric Mobility Ltd.",                           "sector": "Automobile"},
    {"symbol": "OLECTRA.NS",    "name": "Olectra Greentech Ltd.",                               "sector": "Automobile"},
    {"symbol": "ONESOURCE.NS",  "name": "Onesource Specialty Pharma Ltd.",                      "sector": "Healthcare"},
    {"symbol": "ONGC.NS",       "name": "Oil & Natural Gas Corporation Ltd.",                   "sector": "Oil & Gas"},
    {"symbol": "PAGEIND.NS",    "name": "Page Industries Ltd.",                                 "sector": "Textiles"},
    {"symbol": "PARADEEP.NS",   "name": "Paradeep Phosphates Ltd.",                             "sector": "Chemicals"},
    {"symbol": "PATANJALI.NS",  "name": "Patanjali Foods Ltd.",                                 "sector": "FMCG"},
    {"symbol": "PAYTM.NS",      "name": "One 97 Communications Ltd.",                           "sector": "Financial Services"},
    {"symbol": "PCBL.NS",       "name": "PCBL Chemical Ltd.",                                   "sector": "Chemicals"},
    {"symbol": "PERSISTENT.NS", "name": "Persistent Systems Ltd.",                              "sector": "IT"},
    {"symbol": "PETRONET.NS",   "name": "Petronet LNG Ltd.",                                    "sector": "Oil & Gas"},
    {"symbol": "PFC.NS",        "name": "Power Finance Corporation Ltd.",                       "sector": "Financial Services"},
    {"symbol": "PFIZER.NS",     "name": "Pfizer Ltd.",                                          "sector": "Healthcare"},
    {"symbol": "PGEL.NS",       "name": "PG Electroplast Ltd.",                                 "sector": "Consumer Goods"},
    {"symbol": "PHOENIXLTD.NS", "name": "Phoenix Mills Ltd.",                                   "sector": "Real Estate"},
    {"symbol": "PIDILITIND.NS", "name": "Pidilite Industries Ltd.",                             "sector": "Chemicals"},
    {"symbol": "PIIND.NS",      "name": "PI Industries Ltd.",                                   "sector": "Chemicals"},
    {"symbol": "PINELABS.NS",   "name": "Pine Labs Ltd.",                                       "sector": "Financial Services"},
    {"symbol": "PIRAMALFIN.NS", "name": "Piramal Finance Ltd.",                                 "sector": "Financial Services"},
    {"symbol": "PNB.NS",        "name": "Punjab National Bank",                                 "sector": "Financial Services"},
    {"symbol": "PNBHOUSING.NS", "name": "PNB Housing Finance Ltd.",                             "sector": "Financial Services"},
    {"symbol": "POLICYBZR.NS",  "name": "PB Fintech Ltd.",                                      "sector": "Financial Services"},
    {"symbol": "POLYCAB.NS",    "name": "Polycab India Ltd.",                                   "sector": "Capital Goods"},
    {"symbol": "POLYMED.NS",    "name": "Poly Medicure Ltd.",                                   "sector": "Healthcare"},
    {"symbol": "POONAWALLA.NS", "name": "Poonawalla Fincorp Ltd.",                              "sector": "Financial Services"},
    {"symbol": "POWERGRID.NS",  "name": "Power Grid Corporation of India Ltd.",                 "sector": "Power"},
    {"symbol": "POWERINDIA.NS", "name": "Hitachi Energy India Ltd.",                            "sector": "Capital Goods"},
    {"symbol": "PPLPHARMA.NS",  "name": "Piramal Pharma Ltd.",                                  "sector": "Healthcare"},
    {"symbol": "PREMIERENE.NS", "name": "Premier Energies Ltd.",                                "sector": "Capital Goods"},
    {"symbol": "PRESTIGE.NS",   "name": "Prestige Estates Projects Ltd.",                       "sector": "Real Estate"},
    {"symbol": "PTCIL.NS",      "name": "PTC Industries Ltd.",                                  "sector": "Capital Goods"},
    {"symbol": "PVRINOX.NS",    "name": "PVR INOX Ltd.",                                        "sector": "Media & Entertainment"},
    {"symbol": "PWL.NS",        "name": "Physicswallah Ltd.",                                   "sector": "Consumer Services"},
    {"symbol": "RADICO.NS",     "name": "Radico Khaitan Ltd",                                   "sector": "FMCG"},
    {"symbol": "RAILTEL.NS",    "name": "Railtel Corporation Of India Ltd.",                    "sector": "Telecom"},
    {"symbol": "RAINBOW.NS",    "name": "Rainbow Childrens Medicare Ltd.",                      "sector": "Healthcare"},
    {"symbol": "RAMCOCEM.NS",   "name": "The Ramco Cements Ltd.",                               "sector": "Cement"},
    {"symbol": "RBLBANK.NS",    "name": "RBL Bank Ltd.",                                        "sector": "Financial Services"},
    {"symbol": "RECLTD.NS",     "name": "REC Ltd.",                                             "sector": "Financial Services"},
    {"symbol": "REDINGTON.NS",  "name": "Redington Ltd.",                                       "sector": "Services"},
    {"symbol": "RELIANCE.NS",   "name": "Reliance Industries Ltd.",                             "sector": "Oil & Gas"},
    {"symbol": "RHIM.NS",       "name": "RHI MAGNESITA INDIA LTD.",                             "sector": "Capital Goods"},
    {"symbol": "RITES.NS",      "name": "RITES Ltd.",                                           "sector": "Infrastructure"},
    {"symbol": "RKFORGE.NS",    "name": "Ramkrishna Forgings Ltd.",                             "sector": "Automobile"},
    {"symbol": "RPOWER.NS",     "name": "Reliance Power Ltd.",                                  "sector": "Power"},
    {"symbol": "RRKABEL.NS",    "name": "R R Kabel Ltd.",                                       "sector": "Capital Goods"},
    {"symbol": "RVNL.NS",       "name": "Rail Vikas Nigam Ltd.",                                "sector": "Infrastructure"},
    {"symbol": "SAGILITY.NS",   "name": "Sagility Ltd.",                                        "sector": "IT"},
    {"symbol": "SAIL.NS",       "name": "Steel Authority of India Ltd.",                        "sector": "Metals & Mining"},
    {"symbol": "SAILIFE.NS",    "name": "Sai Life Sciences Ltd.",                               "sector": "Healthcare"},
    {"symbol": "SAMMAANCAP.NS", "name": "Sammaan Capital Ltd.",                                 "sector": "Financial Services"},
    {"symbol": "SAPPHIRE.NS",   "name": "Sapphire Foods India Ltd.",                            "sector": "Consumer Services"},
    {"symbol": "SARDAEN.NS",    "name": "Sarda Energy and Minerals Ltd.",                       "sector": "Metals & Mining"},
    {"symbol": "SAREGAMA.NS",   "name": "Saregama India Ltd",                                   "sector": "Media & Entertainment"},
    {"symbol": "SBFC.NS",       "name": "SBFC Finance Ltd.",                                    "sector": "Financial Services"},
    {"symbol": "SBICARD.NS",    "name": "SBI Cards and Payment Services Ltd.",                  "sector": "Financial Services"},
    {"symbol": "SBILIFE.NS",    "name": "SBI Life Insurance Company Ltd.",                      "sector": "Financial Services"},
    {"symbol": "SBIN.NS",       "name": "State Bank of India",                                  "sector": "Financial Services"},
    {"symbol": "SCHAEFFLER.NS", "name": "Schaeffler India Ltd.",                                "sector": "Automobile"},
    {"symbol": "SCHNEIDER.NS",  "name": "Schneider Electric Infrastructure Ltd.",               "sector": "Capital Goods"},
    {"symbol": "SCI.NS",        "name": "Shipping Corporation of India Ltd.",                   "sector": "Services"},
    {"symbol": "SHREECEM.NS",   "name": "Shree Cement Ltd.",                                    "sector": "Cement"},
    {"symbol": "SHRIRAMFIN.NS", "name": "Shriram Finance Ltd.",                                 "sector": "Financial Services"},
    {"symbol": "SHYAMMETL.NS",  "name": "Shyam Metalics and Energy Ltd.",                       "sector": "Capital Goods"},
    {"symbol": "SIEMENS.NS",    "name": "Siemens Ltd.",                                         "sector": "Capital Goods"},
    {"symbol": "SIGNATURE.NS",  "name": "Signatureglobal (India) Ltd.",                         "sector": "Real Estate"},
    {"symbol": "SJVN.NS",       "name": "SJVN Ltd.",                                            "sector": "Power"},
    {"symbol": "SOBHA.NS",      "name": "Sobha Ltd.",                                           "sector": "Real Estate"},
    {"symbol": "SOLARINDS.NS",  "name": "Solar Industries India Ltd.",                          "sector": "Chemicals"},
    {"symbol": "SONACOMS.NS",   "name": "Sona BLW Precision Forgings Ltd.",                     "sector": "Automobile"},
    {"symbol": "SONATSOFTW.NS", "name": "Sonata Software Ltd.",                                 "sector": "IT"},
    {"symbol": "SPLPETRO.NS",   "name": "Supreme Petrochem Ltd.",                               "sector": "Chemicals"},
    {"symbol": "SRF.NS",        "name": "SRF Ltd.",                                             "sector": "Chemicals"},
    {"symbol": "STARHEALTH.NS", "name": "Star Health and Allied Insurance Company Ltd.",        "sector": "Financial Services"},
    {"symbol": "SUMICHEM.NS",   "name": "Sumitomo Chemical India Ltd.",                         "sector": "Chemicals"},
    {"symbol": "SUNDARMFIN.NS", "name": "Sundaram Finance Ltd.",                                "sector": "Financial Services"},
    {"symbol": "SUNPHARMA.NS",  "name": "Sun Pharmaceutical Industries Ltd.",                   "sector": "Healthcare"},
    {"symbol": "SUNTV.NS",      "name": "Sun TV Network Ltd.",                                  "sector": "Media & Entertainment"},
    {"symbol": "SUPREMEIND.NS", "name": "Supreme Industries Ltd.",                              "sector": "Capital Goods"},
    {"symbol": "SUZLON.NS",     "name": "Suzlon Energy Ltd.",                                   "sector": "Capital Goods"},
    {"symbol": "SWANCORP.NS",   "name": "Swan Corp Ltd.",                                       "sector": "Chemicals"},
    {"symbol": "SWIGGY.NS",     "name": "Swiggy Ltd.",                                          "sector": "Consumer Services"},
    {"symbol": "SYNGENE.NS",    "name": "Syngene International Ltd.",                           "sector": "Healthcare"},
    {"symbol": "SYRMA.NS",      "name": "Syrma SGS Technology Ltd.",                            "sector": "Capital Goods"},
    {"symbol": "TARIL.NS",      "name": "Transformers And Rectifiers (India) Ltd.",             "sector": "Capital Goods"},
    {"symbol": "TATACAP.NS",    "name": "Tata Capital Ltd.",                                    "sector": "Financial Services"},
    {"symbol": "TATACHEM.NS",   "name": "Tata Chemicals Ltd.",                                  "sector": "Chemicals"},
    {"symbol": "TATACOMM.NS",   "name": "Tata Communications Ltd.",                             "sector": "Telecom"},
    {"symbol": "TATACONSUM.NS", "name": "Tata Consumer Products Ltd.",                          "sector": "FMCG"},
    {"symbol": "TATAELXSI.NS",  "name": "Tata Elxsi Ltd.",                                      "sector": "IT"},
    {"symbol": "TATAINVEST.NS", "name": "Tata Investment Corporation Ltd.",                     "sector": "Financial Services"},
    {"symbol": "TATAPOWER.NS",  "name": "Tata Power Co. Ltd.",                                  "sector": "Power"},
    {"symbol": "TATASTEEL.NS",  "name": "Tata Steel Ltd.",                                      "sector": "Metals & Mining"},
    {"symbol": "TATATECH.NS",   "name": "Tata Technologies Ltd.",                               "sector": "IT"},
    {"symbol": "TBOTEK.NS",     "name": "TBO Tek Ltd.",                                         "sector": "Consumer Services"},
    {"symbol": "TCS.NS",        "name": "Tata Consultancy Services Ltd.",                       "sector": "IT"},
    {"symbol": "TECHM.NS",      "name": "Tech Mahindra Ltd.",                                   "sector": "IT"},
    {"symbol": "TECHNOE.NS",    "name": "Techno Electric & Engineering Company Ltd.",           "sector": "Infrastructure"},
    {"symbol": "TEGA.NS",       "name": "Tega Industries Ltd.",                                 "sector": "Capital Goods"},
    {"symbol": "TEJASNET.NS",   "name": "Tejas Networks Ltd.",                                  "sector": "Telecom"},
    {"symbol": "TENNIND.NS",    "name": "Tenneco Clean Air India Ltd.",                         "sector": "Automobile"},
    {"symbol": "THELEELA.NS",   "name": "Leela Palaces Hotels & Resorts Ltd.",                  "sector": "Consumer Services"},
    {"symbol": "THERMAX.NS",    "name": "Thermax Ltd.",                                         "sector": "Capital Goods"},
    {"symbol": "TIINDIA.NS",    "name": "Tube Investments of India Ltd.",                       "sector": "Automobile"},
    {"symbol": "TIMKEN.NS",     "name": "Timken India Ltd.",                                    "sector": "Capital Goods"},
    {"symbol": "TITAGARH.NS",   "name": "Titagarh Rail Systems Ltd.",                           "sector": "Capital Goods"},
    {"symbol": "TITAN.NS",      "name": "Titan Company Ltd.",                                   "sector": "Consumer Goods"},
    {"symbol": "TMCV.NS",       "name": "Tata Motors Ltd.",                                     "sector": "Capital Goods"},
    {"symbol": "TMPV.NS",       "name": "Tata Motors Passenger Vehicles Ltd.",                  "sector": "Automobile"},
    {"symbol": "TORNTPHARM.NS", "name": "Torrent Pharmaceuticals Ltd.",                         "sector": "Healthcare"},
    {"symbol": "TORNTPOWER.NS", "name": "Torrent Power Ltd.",                                   "sector": "Power"},
    {"symbol": "TRAVELFOOD.NS", "name": "Travel Food Services Ltd.",                            "sector": "Consumer Services"},
    {"symbol": "TRENT.NS",      "name": "Trent Ltd.",                                           "sector": "Consumer Services"},
    {"symbol": "TRIDENT.NS",    "name": "Trident Ltd.",                                         "sector": "Textiles"},
    {"symbol": "TRITURBINE.NS", "name": "Triveni Turbine Ltd.",                                 "sector": "Capital Goods"},
    {"symbol": "TTML.NS",       "name": "Tata Teleservices (Maharashtra) Ltd.",                 "sector": "Telecom"},
    {"symbol": "TVSMOTOR.NS",   "name": "TVS Motor Company Ltd.",                               "sector": "Automobile"},
    {"symbol": "UBL.NS",        "name": "United Breweries Ltd.",                                "sector": "FMCG"},
    {"symbol": "UCOBANK.NS",    "name": "UCO Bank",                                             "sector": "Financial Services"},
    {"symbol": "ULTRACEMCO.NS", "name": "UltraTech Cement Ltd.",                                "sector": "Cement"},
    {"symbol": "UNIONBANK.NS",  "name": "Union Bank of India",                                  "sector": "Financial Services"},
    {"symbol": "UNITDSPR.NS",   "name": "United Spirits Ltd.",                                  "sector": "FMCG"},
    {"symbol": "UNOMINDA.NS",   "name": "UNO Minda Ltd.",                                       "sector": "Automobile"},
    {"symbol": "UPL.NS",        "name": "UPL Ltd.",                                             "sector": "Chemicals"},
    {"symbol": "URBANCO.NS",    "name": "Urban Company Ltd.",                                   "sector": "Consumer Services"},
    {"symbol": "USHAMART.NS",   "name": "Usha Martin Ltd.",                                     "sector": "Capital Goods"},
    {"symbol": "UTIAMC.NS",     "name": "UTI Asset Management Company Ltd.",                    "sector": "Financial Services"},
    {"symbol": "VBL.NS",        "name": "Varun Beverages Ltd.",                                 "sector": "FMCG"},
    {"symbol": "VEDL.NS",       "name": "Vedanta Ltd.",                                         "sector": "Metals & Mining"},
    {"symbol": "VIJAYA.NS",     "name": "Vijaya Diagnostic Centre Ltd.",                        "sector": "Healthcare"},
    {"symbol": "VMM.NS",        "name": "Vishal Mega Mart Ltd.",                                "sector": "Consumer Services"},
    {"symbol": "VOLTAS.NS",     "name": "Voltas Ltd.",                                          "sector": "Consumer Goods"},
    {"symbol": "VTL.NS",        "name": "Vardhman Textiles Ltd.",                               "sector": "Textiles"},
    {"symbol": "WAAREEENER.NS", "name": "Waaree Energies Ltd.",                                 "sector": "Capital Goods"},
    {"symbol": "WELCORP.NS",    "name": "Welspun Corp Ltd.",                                    "sector": "Capital Goods"},
    {"symbol": "WELSPUNLIV.NS", "name": "Welspun Living Ltd.",                                  "sector": "Textiles"},
    {"symbol": "WHIRLPOOL.NS",  "name": "Whirlpool of India Ltd.",                              "sector": "Consumer Goods"},
    {"symbol": "WIPRO.NS",      "name": "Wipro Ltd.",                                           "sector": "IT"},
    {"symbol": "WOCKPHARMA.NS", "name": "Wockhardt Ltd.",                                       "sector": "Healthcare"},
    {"symbol": "YESBANK.NS",    "name": "Yes Bank Ltd.",                                        "sector": "Financial Services"},
    {"symbol": "ZEEL.NS",       "name": "Zee Entertainment Enterprises Ltd.",                   "sector": "Media & Entertainment"},
    {"symbol": "ZENSARTECH.NS", "name": "Zensar Technolgies Ltd.",                              "sector": "IT"},
    {"symbol": "ZENTEC.NS",     "name": "Zen Technologies Ltd.",                                "sector": "Capital Goods"},
    {"symbol": "ZFCVINDIA.NS",  "name": "ZF Commercial Vehicle Control Systems India Ltd.",     "sector": "Automobile"},
    {"symbol": "ZYDUSLIFE.NS",  "name": "Zydus Lifesciences Ltd.",                              "sector": "Healthcare"},
    {"symbol": "ZYDUSWELL.NS",  "name": "Zydus Wellness Ltd.",                                  "sector": "FMCG"},
]

# ─── Registry ─────────────────────────────────────────────────────────────────
UNIVERSES: dict[str, list[dict]] = {
    "NIFTY50":  NIFTY50_STOCKS,
    "NIFTY500": NIFTY500_STOCKS,
}


def get_stocks(universe: str = "NIFTY50") -> list[dict]:
    """Return all stock dicts for the given universe, including any custom tickers."""
    base = UNIVERSES.get(universe, NIFTY50_STOCKS)
    custom = _get_custom_stocks_from_db()
    if not custom:
        return base
    # Avoid duplicates: existing symbols in base take priority
    existing_syms = {s["symbol"] for s in base}
    extras = [c for c in custom if c["symbol"] not in existing_syms]
    return base + extras


def get_symbols(universe: str = "NIFTY50") -> list[str]:
    return [s["symbol"] for s in get_stocks(universe)]


def get_sectors(universe: str = "NIFTY50") -> dict[str, list[str]]:
    """Return a mapping of sector name → list of symbols."""
    sectors: dict[str, list[str]] = {}
    for stock in get_stocks(universe):
        sectors.setdefault(stock["sector"], []).append(stock["symbol"])
    return sectors


def get_symbol_to_name(universe: str = "NIFTY50") -> dict[str, str]:
    return {s["symbol"]: s["name"] for s in get_stocks(universe)}


def get_symbol_to_sector(universe: str = "NIFTY50") -> dict[str, str]:
    return {s["symbol"]: s["sector"] for s in get_stocks(universe)}
